### ISSUE TITLE
`DeviceList` not working on macOS 11

### ISSUE THREAD

**Issue by nvmnghia** [truenas/py-SMART#43] opened 2021-12-12 06:03 UTC
This line fails:

https://github.com/truenas/py-SMART/blob/68aeea9ce09b1875286eb9549e60516c7fb4bbc4/pySMART/device_list.py#L105

System: 

- macOS 11.6.1
- Python 3.9.9
- pySMART latest on PyPI
- smartctl 7.2 2020-12-30 r5155

The regex doesn't work because `line` doesn't match:

```text
>>> print(line)
IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SAT0@1F,2/AppleIntelPchSeriesAHCI/SPT4@4/IOAHCIDevice@0/AppleAHCIDiskDriver/IOAHCIBlockStorageDevice -d ata # IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SAT0@1F,2/AppleIntelPchSeriesAHCI/SPT4@4/IOAHCIDevice@0/AppleAHCIDiskDriver/IOAHCIBlockStorageDevice, ATA device
```

**Comment by ralequi** [comment] 2021-12-13 10:47
Hi @nvmnghia 

Could you provide the complete output of the following commands?

```
smartctl --scan-open
smartctl -d ata --all <whole path to your falling device>
```

It would be nice to add a disk from MacOS to the test dataset.

Thank you!

**Comment by nvmnghia** [comment] 2021-12-13 21:10
```text
>>> smartctl --scan-open

IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SAT0@1F,2/AppleIntelPchSeriesAHCI/SPT4@4/IOAHCIDevice@0/AppleAHCIDiskDriver/IOAHCIBlockStorageDevice -d ata # IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SAT0@1F,2/AppleIntelPchSeriesAHCI/SPT4@4/IOAHCIDevice@0/AppleAHCIDiskDriver/IOAHCIBlockStorageDevice, ATA device
IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SAT0@1F,2/AppleIntelPchSeriesAHCI/PRT2@2/IOAHCIDevice@0/AppleAHCIDiskDriver/IOAHCIBlockStorageDevice -d ata # IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SAT0@1F,2/AppleIntelPchSeriesAHCI/PRT2@2/IOAHCIDevice@0/AppleAHCIDiskDriver/IOAHCIBlockStorageDevice, ATA device
```

The script

```python
from pySMART import Device
Device('/dev/disk1')
```

seems OK to me, so there's no failing device for my case.

**Comment by ralequi** [comment] 2021-12-14 16:25
Please, check the last commit at master and confirm that everything works

**Comment by nvmnghia** [comment] 2021-12-20 15:51
Sorry for not getting back immediately.

Now it doesn't print anything. I tracked down to this: the `name` in this line

https://github.com/truenas/py-SMART/blob/68aeea9ce09b1875286eb9549e60516c7fb4bbc4/pySMART/device_list.py#L106

is `/dev/IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SAT0@1F,2/AppleIntelPchSeriesAHCI/SPT4@4/IOAHCIDevice@0/AppleAHCIDiskDriver/IOAHCIBlockStorageDevice`.

**Comment by ralequi** [comment] 2022-07-18 10:19
Sorry @nvmnghia I absolutely forget about this issue.

Just to confirm I've understood this correctly:

The following command does not work ( which seems logic):
- `smartctl -d ata --all '/dev/IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SAT0@1F,2/AppleIntelPchSeriesAHCI/SPT4@4/IOAHCIDevice@0/AppleAHCIDiskDriver/IOAHCIBlockStorageDevice'`

The correct one should be:
- `smartctl -d ata --all 'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SAT0@1F,2/AppleIntelPchSeriesAHCI/SPT4@4/IOAHCIDevice@0/AppleAHCIDiskDriver/IOAHCIBlockStorageDevice'`

Please, confirm me when you are able that the previous command works, if not, please, provide me the custom command with smartctl that allows you to access your device

Thanks for your help

**Comment by ralequi** [comment] 2022-08-29 15:02
Hi @nvmnghia ,

A MacOs user with `12.4` tould me that command `smartctl --scan-open` does nothing currently.
Could you please check again if you have 12.4 version? Or if you find time, reply to my latests comment would be nice too.

Any other info would be appreciated

**Comment by nvmnghia** [comment] 2022-08-29 18:14
> Sorry @nvmnghia I absolutely forget about this issue.
> 
> Just to confirm I've understood this correctly:
> 
> The following command does not work ( which seems logic):
> 
> * `smartctl -d ata --all '/dev/IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SAT0@1F,2/AppleIntelPchSeriesAHCI/SPT4@4/IOAHCIDevice@0/AppleAHCIDiskDriver/IOAHCIBlockStorageDevice'`
> 
> The correct one should be:
> 
> * `smartctl -d ata --all 'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/SAT0@1F,2/AppleIntelPchSeriesAHCI/SPT4@4/IOAHCIDevice@0/AppleAHCIDiskDriver/IOAHCIBlockStorageDevice'`
> 
> Please, confirm me when you are able that the previous command works, if not, please, provide me the custom command with smartctl that allows you to access your device
> 
> Thanks for your help

That second command works. My hackintosh is stuck at 11.6, so I can't help you with that :(.

**Comment by ralequi** [comment] 2022-08-30 17:57
I think pysmart is broken on MacOs 12, however, until I have more data I can't do much more...

In any case, I think for MacOs 11 should be fixed. Please, try the develop branch ( https://github.com/truenas/py-SMART/tree/develop ) whenerver you can and tell me if you find any other issues.

Thank you!

**Comment by ralequi** [comment] 2022-08-31 12:18
I'm going to close the issue, please, feel free to reopen it if you find the problem is still there on MacOS 11.x

Thank you!

**Closed by ralequi** 2022-08-31 12:18 UTC
Labels: bug, needs more info, MacOS
